name: Python package


on: 
  push:
    branches:
      - master
  pull_request:
     branches:
      - master

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - name: Check out source repository # Название шага, который будет отображаться при прогоне
        uses: actions/checkout@v3
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # Install pip and pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install pyinstaller
          pip install -r requirements.txt
      - name: Run flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#       - name: Run PyInstaller
#         run: |
#           pyinstaller --add-data "netflix_titles.csv;." simple1.py
      - name: Run tests
        run: |
          pytest tests
#       - name: Run test_SaveBatch
#         run: |
#           pytest tests/test_SaveBatch.py
#       - name: Run test_SaveLoadModel
#         run: |
#           pytest tests/test_SaveLoadModel.py
#       - name: Run test_TestNetwork
#         run: |
#           pytest tests/test_TestNetwork.py


      #  Compares two code coverage files and generates report as a comment
      - name: Get Cover 
        uses: orgoro/coverage@v3.1
        with:
          coverageFile: path/to/coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
