name: Python package

# Этот блок отвечает за то, что при каждом push и pull-request
# на ветку master запускается тестирование 
on: 
  push:
    branches:
      - master
  pull_request:
     branches:
      - master
# Это блоки работы, то есть здесь мы можем хоть как назвать блко( например, тут это
# build-windows) и выбирать виртуальную машину для прогона ( в моем случае это windows-latest)
# а дальше по шагам прогоняем все, что нам необходимо
jobs:
  build-windows:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - name: Check out source repository # Название шага, который будет отображаться при прогоне
        uses: actions/checkout@v3
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # Install pip and pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install pyinstaller
          pip install -r requirements.txt
      - name: Run flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#       - name: Run PyInstaller
#         run: |
#           pyinstaller --add-data "netflix_titles.csv;." simple1.py
      - name: Run tests
        run: |
          pytest tests
#       - name: Run test_SaveBatch
#         run: |
#           pytest tests/test_SaveBatch.py
#       - name: Run test_SaveLoadModel
#         run: |
#           pytest tests/test_SaveLoadModel.py
#       - name: Run test_TestNetwork
#         run: |
#           pytest tests/test_TestNetwork.py
#       - name: Code Coverage Report
#         uses: irongut/CodeCoverageSummary@v1.3.0
#         with:
#           filename: coverage/**/coverage.cobertura.xml
#           badge: true
#           fail_below_min: true
#           format: markdown
#           hide_branch_rate: false
#           hide_complexity: true
#           indicators: true
#           output: both
#           thresholds: '60 80'

#       - name: Add Coverage PR Comment
#         uses: marocchino/sticky-pull-request-comment@v2
#         if: github.event_name == 'pull_request'
#         with:
#           recreate: true
#           path: code-coverage-results.md
